### ISSUE TITLE
Basics Git and Github and Command line

### ISSUE THREAD

**Issue by touraye** [aayaat/web-development#2]
Create a projects directory called **02-getting-started-with-git-and-github-and-command-line-basics**, within, i create a README.md and another directory called  **01-introdution-to-git-and-github**. In the 01-introduction-to-git-github i create a README.md and a directory called assets, within i have images for the README.md.

**Comment by kamariana** [comment]
Thanks for this, please can you do the name like the following:
the root folder to 02-command-line-basics-and-introduction-to-git

then within that folder, have the following folders and files
- README.md
- 01-command-line-basics 
- 02-setting-up-git
- 03-introduction-to-git
- 04-git-basics

within the sub folders have a README.md to introduce the topic. the main readme on should highlight all the topics

**Comment by touraye** [comment]
Change the root directory name from **02-getting-started-with-git-and-github-and-command-line-basics** to **02-command-line-basics-and-introduction-to-git**, add a README .md file in the root and introduce the topics. add four sub directories in the root directory each contain a README.md file were i talk about some basics.
The sub directories i added:
* 01-commad-lina-basics
* 02-setting-up-git
* 03-introduction-to-git
* 04-git-basics

**Comment by kamariana** [comment]
All good
